version: '3.8'
services:
  # sfs-discord-server:
  #   # SFSをghcr.ioにアップロードし参照する
  #   image: anything

  minecraft-bedrock-server-1:
    image: itzg/minecraft-bedrock-server
    container_name: mc-bedrock-server-1
    restart: always
    environment:
      EULA: "TRUE"
      VERSION: LATEST
      GAMEMODE: survival
      DIFFICULTY: normal
      SERVER_NAME: FEATO
      MAX_THREADS: 0
      VIEW_DISTANCE: 20
      CONTENT_LOG_FILE_ENABLED: true
    ports:
      - 19132:19132/udp
    volumes:
      - minecraft-bedrock-server-1-data-volume:/data
    stdin_open: true
    tty: true
    networks:
      - minecraft-network
    deploy:
      resources:
        limits:
          memory: 3G

volumes:
  minecraft-bedrock-server-1-data-volume: {}
  minecraft-bedrock-backup-1-backups-volume: {}

networks:
  minecraft-network:
