version: '3.8'
services:
  # sfs-discord-server:
  #   # SFSをghcr.ioにアップロードし参照する
  #   image: anything

  minecraft-bedrock-server-1:
    image: itzg/minecraft-bedrock-server
    container_name: mc-bedrock-server-1
    environment:
      EULA: "TRUE"
      VERSION: LATEST
      GAMEMODE: survival
      DIFFICULTY: normal
      SERVER_NAME: FEATO
      MAX_THREADS: 0
      VIEW_DISTANCE: 20
      CONTENT_LOG_FILE_ENABLED: "TRUE"
      PLAYER_IDLE_TIMEOUT: 90
    ports:
      - "19132:19132/udp"
    volumes:
      - minecraft-bedrock-server-1-data-volume:/data
    stdin_open: true
    tty: true
    networks:
      - minecraft-network
    depends_on:
      - fluent-bit
    deploy:
      resources:
        limits:
          memory: 3G
    logging:
      driver: fluentd
      options:
        tag: "minecraft-server"

  fluent-bit:
    image: fluent/fluent-bit
    env_file: .env
    volumes:
      - ./fluentbit:/fluent-bit/etc/
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "24224:24224"
    stdin_open: true
    tty: true
    networks:
      - minecraft-network
    deploy:
      resources:
        limits:
          memory: 150M
      update_config:
        delay: 20s
    logging:
      options:
        max-size: 10m

  minecraft-monitor:
    image: itzg/mc-monitor
    command: export-for-prometheus
    environment:
      EXPORT_BEDROCK_SERVERS: minecraft-bedrock-server-1
      DEBUG: "true"
    networks:
      - minecraft-network
    depends_on:
      - minecraft-bedrock-server-1
    deploy:
      resources:
        limits:
          memory: 80M
    logging:
      options:
        max-size: 10m

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - minecraft-network
    depends_on:
      - fluent-bit
    deploy:
      resources:
        limits:
          memory: 80M
    logging:
      options:
        max-size: 10m

volumes:
  minecraft-bedrock-server-1-data-volume: {}
  minecraft-bedrock-backup-1-backups-volume: {}

networks:
  minecraft-network:
