version: "3.8"
services:
  sfs-discord-server:
    image: ghcr.io/feato-org/support-feato-system:main
    env_file: .env
    networks:
      - fluent-network
    deploy:
      resources:
        limits:
          memory: 20M
      restart_policy:
        delay: 15s
    logging:
      driver: fluentd
      options:
        tag: "sfs_discord_server_log"
        fluentd-address: fluent-bit:24224

  fluent-bit:
    image: fluent/fluent-bit:2.2.2
    env_file: .env
    volumes:
      - ./fluentbit:/fluent-bit/etc/
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    stdin_open: true
    tty: true
    networks:
      - fluent-network
    deploy:
      resources:
        limits:
          memory: 70M
      update_config:
        delay: 20s
    logging:
      options:
        max-size: 10m

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - fluent-network
    depends_on:
      - fluent-bit
    deploy:
      resources:
        limits:
          memory: 70M
    logging:
      options:
        max-size: 10m

  portainer-agent:
    image: portainer/agent:2.19.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer-network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    logging:
      options:
        max-size: 10m

  portainer-host:
    image: portainer/portainer-ee:2.19.4
    command: -H tcp://portainer-agent:9001 --tlsskipverify
    environment:
    - VIRTUAL_HOST=${PORTAINER_HOST}
    - VIRTUAL_PORT=9000
    - LETSENCRYPT_HOST=${PORTAINER_HOST}
    - LETSENCRYPT_EMAIL=${DEFAULT_EMAIL}
    ports:
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - portainer-network
      - nginx-network
      - fluent-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    logging:
      driver: fluentd
      options:
        tag: "portainer_host__log"
        fluentd-address: fluent-bit:24224

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-network
      - fluent-network
    deploy:
      resources:
        limits:
          memory: 60M
    logging:
      driver: fluentd
      options:
        tag: "nginx_proxy_log"
        fluentd-address: fluent-bit:24224

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    environment:
      - ACME_CA_URI=${ACME_CA_URI}
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    networks:
      - nginx-network
    deploy:
      resources:
        limits:
          memory: 32M
    logging:
      options:
        max-size: 10m

volumes:
  minecraft-bedrock-server-1-data-volume: {}
  minecraft-server-1-data-volume: {}
  minecraft-backup-1-backups-volume: {}
  portainer_data: {}
  certs: {}
  vhost: {}
  html: {}
  acme: {}
  minecraft-proxy-server-volume: {}

networks:
  fluent-network:
  portainer-network:
    driver: overlay
    attachable: true
  nginx-network:
