FROM cr.fluentbit.io/fluent/fluent-bit:5.1.2
LABEL org.opencontainers.image.source="https://github.com/FEATO-org/it-infrastructure-server"
COPY fluentbit/fluent-bit.conf fluentbit/parsers.conf fluentbit/discord.lua /fluent-bit/etc/
