[SERVICE]
  Flush                     5
  Grace                     30
  Log_Level                 info
  Parsers_File              parsers.conf
  storage.path              /fluent-bit/state
  storage.sync              normal
  storage.checksum          off
  storage.backlog.mem_limit 20M

[INPUT]
  Name              tail
  Tag               logs.docker.*
  Path              /var/lib/docker/containers/*/*.log
  Path_Key          source
  Parser            docker
  DB                /fluent-bit/state/docker-tail.db
  DB.Sync           normal
  Mem_Buf_Limit     50M
  Skip_Long_Lines   On
  Refresh_Interval  10
  Rotate_Wait       30
  storage.type      filesystem

[INPUT]
  Name  docker_events
  Tag   event.system.docker

[FILTER]
  Name  rewrite_tag
  Match logs.docker.*
  Rule  $log (emerg|alert|crit|err|fail|ERR) notify.error true

[FILTER]
  Name  rewrite_tag
  Match logs.docker.*
  Rule  $log ((joined|left)\sthe\sgame) notify.login_and_logout true

[FILTER]
  Name  rewrite_tag
  Match event.system.docker
  Rule  $message "status":"(oom|kill|die|stop|restart|start)" notify.container_event true

[FILTER]
  Name          record_modifier
  Match         notify.login_and_logout
  Allowlist_key log

[OUTPUT]
  Name        loki
  Match       logs.docker.*
  Host        logs-prod-011.grafana.net
  Port        443
  TLS         On
  TLS.Verify  On
  HTTP_User   ${LOKI_USER_ID}
  HTTP_Passwd ${GRAFANA_API_KEY}
  Labels      app_mode=${APP_MODE}

[OUTPUT]
  Name    slack
  Match   notify.error
  Webhook ${ERROR_WEBHOOK_URL}

[OUTPUT]
  Name    slack
  Match   notify.login_and_logout
  Webhook ${NOTIFY_WEBHOOK_URL}

[OUTPUT]
  Name    slack
  Match   notify.container_event
  Webhook ${NOTIFY_WEBHOOK_URL}
