[SERVICE]
  Flush                     5
  Grace                     30
  Log_Level                 info
  Parsers_File              parsers.conf
  storage.path              /fluent-bit/state
  storage.sync              normal
  storage.checksum          off
  storage.backlog.mem_limit 20M

[INPUT]
  Name              tail
  Tag               logs.docker.*
  Path              /var/lib/docker/containers/*/*.log
  Path_Key          source
  Parser            docker
  DB                /fluent-bit/state/docker-tail.db
  DB.Sync           normal
  Mem_Buf_Limit     50M
  Skip_Long_Lines   On
  Refresh_Interval  10
  Rotate_Wait       30
  storage.type      filesystem

[INPUT]
  Name              tail
  Tag               minecraft.latest
  Path              /minecraft/logs/latest.log
  DB                /fluent-bit/state/minecraft-tail.db
  DB.Sync           normal
  Read_from_Head    false
  Mem_Buf_Limit     10M
  Skip_Long_Lines   On
  Refresh_Interval  10
  Rotate_Wait       30
  storage.type      filesystem

[FILTER]
  Name    lua
  Match   minecraft.latest
  Script  /fluent-bit/etc/discord.lua
  Call    process_minecraft_log

[OUTPUT]
  Name                  http
  Match                 minecraft.latest
  Host                  ${DISCORD_WEBHOOK_HOST}
  Port                  443
  URI                   ${DISCORD_WEBHOOK_URI}
  TLS                   On
  TLS.Verify            On
  Body_Key              $body
  Headers_Key           $headers
  Log_Response_Payload  false
  Retry_Limit           5

[OUTPUT]
  Name        loki
  Match       logs.docker.*
  Host        logs-prod-011.grafana.net
  Port        443
  TLS         On
  TLS.Verify  On
  HTTP_User   ${LOKI_USER_ID}
  HTTP_Passwd ${GRAFANA_API_KEY}
  Labels      app_mode=${APP_MODE}
