# system stack
version: "3.8"
services:
  fluent-bit:
    image: fluent/fluent-bit:2.2.2
    ports:
      - "127.0.0.1:24224:24224"
    environment:
      - NOTIFY_WEBHOOK_URL
      - ERROR_WEBHOOK_URL
      - PROM_USER_ID
      - LOKI_USER_ID
      - GRAFANA_API_KEY
      - APP_MODE
    volumes:
      - type: bind
        source: ../../fluentbit/
        target: /fluent-bit/etc/
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - fluent-network
    deploy:
      resources:
        limits:
          memory: 100M
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    logging:
      options:
        max-size: 10m

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    expose:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - fluent-network
    depends_on:
      - fluent-bit
    deploy:
      resources:
        limits:
          memory: 70M
    logging:
      driver: fluentd
      options:
        tag: "logs.docker.cadvisor"
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"
        fluentd-buffer-limit: 1000
        fluentd-max-retries: 300

  minecraft-monitor:
    image: itzg/mc-monitor
    command: export-for-prometheus
    expose:
      - "8080"
    environment:
      EXPORT_SERVERS: app_minecraft-spigot-server
    depends_on:
      - fluent-bit
    deploy:
      resources:
        limits:
          memory: 100M
    logging:
      driver: fluentd
      options:
        tag: "logs.docker.minecraft-monitor"
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"
        fluentd-retry-wait: 5s
        fluentd-buffer-limit: 1000
        fluentd-max-retries: 300

networks:
  fluent-network:
    attachable: true
