# app stack
version: "3.8"
services:
  # discord
  sfs-discord-server:
    image: ghcr.io/feato-org/support-feato-system:main
    environment:
      - DISCORD_TOKEN
      - GUILD_IDS
      - APP_MODE
      - NOTIFY_CHANNEL_ID
    networks:
      - system_fluent-network
    deploy:
      resources:
        limits:
          memory: 20M
      restart_policy:
        # DiscordAPIを叩きすぎないようにするため
        delay: 15s
    logging:
      driver: fluentd
      options:
        tag: "logs.docker.sfs-discord-server"
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "false"

  # minecraft
  minecraft-proxy:
    image: itzg/bungeecord:java21
    environment:
      TYPE: VELOCITY
      MEMORY: ""
      TZ: Asia/Tokyo
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75 -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15"
      ICON: https://photo.feato.jp/_data/i/upload/2023/06/24/20230624012009-7add3e01-xl.png
      PLUGINS: https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/velocity,https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/velocity
    ports:
      - "25565:25577"
      - "19132:19132/udp"
    secrets:
      - forwarding_secret
    volumes:
      - minecraft_proxy_data:/server
      - ../../minecraft-proxy/plugins:/plguins
      - /extras/texturepacks:/plguins/Geyser-Velocity/packs
      - ../../minecraft-proxy/config:/config
    networks:
      - minecraft-network
      - system_fluent-network
    deploy:
      resources:
        limits:
          memory: 1G
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    logging:
      driver: fluentd
      options:
        tag: "logs.docker.minecraft-proxy"
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "false"

  minecraft-spigot-server:
    image: itzg/minecraft-server:java21
    environment:
      # proxy向け設定
      ONLINE_MODE: "FALSE"
      NETWORK_COMPRESSION_THRESHOLD: -1
      MEMORY: 4800M
      TYPE: SPIGOT
      USE_AIKAR_FLAGS: "TRUE"
      EULA: "TRUE"
      VERSION: LATEST
      GAMEMODE: survival
      DIFFICULTY: normal
      SERVER_NAME: FEATO
      SPAWN_PROTECTION: 0
      PLAYER_IDLE_TIMEOUT: 90
      VIEW_DISTANCE: 14
      SIMULATION_DISTANCE: 8
      TZ: Asia/Tokyo
      # TreeAssist,Simply Farming,FarmProtect,BetterChairs Remastered,new-new-gods,DualHorse,backpack-plus
      SPIGET_RESOURCES: "67436,110400,87480,84809,89188,99663,109630"
      PLUGINS_FILE: /extras/plugins.txt
      DATAPACKS: /extras/datapacks
      # RESOURCE_PACK: /extras/resourcepacks
      ENABLE_COMMAND_BLOCK: "TRUE"
      # spigot用
      COPY_CONFIG_DEST: /data
      LOG_TIMESTAMP: "TRUE"
      GUI: "FALSE"
      ICON: https://photo.feato.jp/_data/i/upload/2023/06/24/20230624012009-7add3e01-xl.png
      SEED: ""
      RESOURCE_PACK_ENFORCE: "TRUE"
      ENFORCE_SECURE_PROFILE: "FALSE"
      SPIGOT_DOWNLOAD_URL: https://storage.feato.jp/index.php/s/MkLFA4XBnfcs5ic/download/spigot-1.21.jar
    ports:
      - "8123:8123"
    expose:
      - "25565"
    volumes:
      - minecraft_server_data:/data
      # plugins download
      - ../../minecraft/java/plugins.txt:/extras/plugins.txt:ro
      # - /extras/plugins:/plugins
      # datapack
      - /extras/datapacks:/extras/datapacks
      # resourcepack
      # - /extras/resourcepacks:/extras/resourcepacks
      # config
      - ../../minecraft/java/config:/config
    networks:
      - minecraft-network
      - nginx-network
    depends_on:
      - fluent-bit
    deploy:
      resources:
        limits:
          memory: 6G
    logging:
      driver: fluentd
      options:
        tag: "logs.docker.minecraft-server"
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "false"

  # Web系
  nginx:
    image: nginx:1.27.0
    command: 'nginx -g "daemon off;"'
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: Asia/Tokyo
      PORTAINER_URL:
    volumes:
      - type: bind
        source: ../../nginx/templates
        target: /etc/nginx/templates
        read_only: true
      - type: bind
        source: ../../nginx/sites-available
        target: /etc/nginx/sites-available
        read_only: true
      - type: bind
        source: ../../nginx/sites-enabled
        target: /etc/nginx/sites-enabled
        read_only: true
      # - type: bind
      #   source: ../../nginx/html
      #   target: /usr/share/nginx/html
      #   read_only: true
      - certs:/etc/letsencrypt:ro
    networks:
      - nginx-network
      - cert-network
      - system_fluent-network
    deploy:
      resources:
        limits:
          memory: 100M
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    logging:
      driver: fluentd
      options:
        tag: "logs.docker.nginx"
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "false"

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 10d & wait $${!}; done;'"
    volumes:
      - certs:/etc/letsencrypt
    networks:
      - cert-network
      - system_fluent-network
    deploy:
      resources:
        limits:
          memory: 100M
    logging:
      driver: fluentd
      options:
        tag: "logs.docker.certbot"
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"
        fluentd-retry-wait: 5s
        fluentd-buffer-limit: 2000
        fluentd-max-retries: 100

volumes:
  certs: {}
  minecraft_server_data: {}
  minecraft_proxy_data: {}

secrets:
  forwarding_secret:
    external: true

networks:
  system_fluent-network:
    external: true
  nginx-network:
    attachable: true
  cert-network:
    attachable: false
  minecraft-network:
    attachable: true
