# app stack
version: "3.8"
services:
  sfs-discord-server:
    image: ghcr.io/feato-org/support-feato-system:main
    environment:
      - DISCORD_TOKEN
      - GUILD_IDS
      - APP_MODE
      - NOTIFY_CHANNEL_ID
    networks:
      - system_fluent-network
    deploy:
      resources:
        limits:
          memory: 20M
      restart_policy:
        delay: 15s
    logging:
      driver: fluentd
      options:
        tag: "sfs_discord_server_log"
        fluentd-async: "true"

  nginx:
    image: nginx:1.27.0
    command: '/bin/sh -c ''while :; do sleep 20d & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: Asia/Tokyo
      PORTAINER_URL:
    volumes:
      - type: bind
        source: ../../nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
      - type: bind
        source: ../../nginx/templates
        target: /etc/nginx/templates
        read_only: true
      - type: bind
        source: ../../nginx/sites-available
        target: /etc/nginx/sites-available
        read_only: true
      - type: bind
        source: ../../nginx/sites-enabled
        target: /etc/nginx/sites-enabled
        read_only: true
      - type: bind
        source: ../../nginx/html
        target: /usr/share/nginx/html
        read_only: true
      - certs:/etc/letsencrypt:ro
    networks:
      - nginx-network
      - cert-network
      - system_fluent-network
    logging:
      driver: fluentd
      options:
        tag: "nginx_log"
        fluentd-async: "true"
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 10d & wait $${!}; done;'"
    volumes:
      - certs:/etc/letsencrypt
    networks:
      - cert-network
      - system_fluent-network
    logging:
      driver: fluentd
      options:
        tag: "certbot_log"
        fluentd-async: "true"

volumes:
  certs: {}

networks:
  system_fluent-network:
    external: true
  nginx-network:
    attachable: true
  cert-network:
    attachable: false
