services:
  portainer-host:
    image: portainer/portainer-ee:2.19.4
    command: -H unix:///var/run/docker.sock
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - fluent-network
      - nginx-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    logging:
      driver: fluentd
      options:
        tag: "portainer_host_log"
        fluentd-async: "true"

volumes:
  portainer_data:

networks:
  fluent-network:
    attachable: true
    external: true
  nginx-network:
    attachable: true
    external: true
