# infra stack
services:
  portainer-agent:
    image: portainer/agent:2.30.1
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
    expose:
      - "9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent-network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      resources:
        limits:
          memory: 100M
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    logging:
      driver: fluentd
      options:
        tag: "logs.docker.portainer-agent"
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"
        fluentd-retry-wait: 5s

  portainer-host:
    image: portainer/portainer-ee:2.30.1
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - portainer_agent-network
      - system_fluent-network
      - app_nginx-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 150M
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    logging:
      driver: fluentd
      options:
        tag: "logs.docker.portainer-host"
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"
        fluentd-retry-wait: 5s

volumes:
  portainer_data:

networks:
  system_fluent-network:
    external: true
  app_nginx-network:
    external: true
  portainer_agent-network:
