# infra stack
version: "3.8"
services:
  portainer-agent:
    image: portainer/agent:2.20.3
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
    expose:
      - "9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent-network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    logging:
      driver: fluentd
      options:
        tag: "docker.portainer-agent"
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"
        fluentd-retry-wait: 5
        fluentd-buffer-limit: 2000
        fluentd-max-retries: 100

  portainer-host:
    image: portainer/portainer-ee:2.20.3
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - portainer_agent-network
      - system_fluent-network
      - system_nginx-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    logging:
      driver: fluentd
      options:
        tag: "docker.portainer-host"
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "false"

volumes:
  portainer_data:

networks:
  system_fluent-network:
    external: true
  system_nginx-network:
    external: true
  portainer_agent-network:
