# infra stack
version: "3.8"
services:
  portainer-agent:
    image: portainer/agent:2.20.3
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
    expose:
      - "9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent-network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    logging:
      options:
        max-size: 10m
  portainer-host:
    image: portainer/portainer-ee:2.20.3
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - portainer_agent-network
      - system_fluent-network
      - system_nginx-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    logging:
      options:
        max-size: 10m
    # logging:
    #   driver: fluentd
    #   options:
    #     tag: "portainer_host_log"
    #     fluentd-async: "true"

volumes:
  portainer_data:

networks:
  system_fluent-network:
    external: true
  system_nginx-network:
    external: true
  portainer_agent-network:
