---
- name: docker swarm deploy
  hosts: all
  tasks:
    - name: Init a new swarm with default parameters
      community.docker.docker_swarm:
        state: present

    - name: Add nodes
      community.docker.docker_swarm:
        state: join

    - name: Deploy
      community.docker.docker_stack:
        name: minecraft-stack
        compose: ./compose.yml
